services: 
  app:
    image: sixriz/app-java-spring-boot:latest
    restart: always
    container_name: app-java-spring-boot
    ports:
      - "8081:8072"
    volumes:
      - ./docker_application.properties:/app/application.properties:ro
    depends_on:
      - db
      - redis
    networks:
      - app-net

  db:
    image: mysql:8
    restart: always
    container_name: db-mysql
    volumes:
      - ./.docker/data/db-sql:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: demo_app
    networks:
      - app-net
    user: "1002:1002"

  redis:
    image: redis:6-alpine
    restart: always
    container_name: redis
    volumes:
      - ./.docker/data/redis:/data
    networks:
      - app-net
    user: "1002:1002"

networks:
  app-net:
    driver: bridge